# -*- coding: utf-8 -*-
"""Questões Cap.6 | CEP | Isadora Messenberg 231013387

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyF7Y0B2gQ9Zbd4iWFt_qpzKUT3y7lBM
"""

# ── IMPORTAÇÃO DE BIBLIOTECAS ────────────────────────────────
import numpy as np            # operações matemáticas e arrays
import pandas as pd           # manipulação de tabelas (DataFrames)
import matplotlib.pyplot as plt        # geração de gráficos
import matplotlib.gridspec as gridspec # layout avançado de subplots
from scipy import stats       # funções estatísticas (normal, probplot)
import warnings
warnings.filterwarnings('ignore')  # oculta avisos desnecessários na saída

# ── CONFIGURAÇÕES GLOBAIS DE PLOTAGEM ────────────────────────
plt.rcParams['figure.figsize'] = (12, 5)  # tamanho padrão de todas as figuras
plt.rcParams['font.size'] = 10            # tamanho padrão de fonte nos gráficos


# ════════════════════════════════════════════════════════════
# TABELA DE CONSTANTES PARA GRÁFICOS DE CONTROLE
# ════════════════════════════════════════════════════════════
# Dicionário com as constantes tabeladas para cada tamanho de
# subgrupo n. Cada chave n mapeia para uma tupla com:
#   índice 0 → A2  : fator para limites do gráfico X̄ usando R
#   índice 1 → D3  : fator para limite inferior do gráfico R
#   índice 2 → D4  : fator para limite superior do gráfico R
#   índice 3 → d2  : fator de escala para estimar σ via R̄
#   índice 4 → A3  : fator para limites do gráfico X̄ usando s
#   índice 5 → B3  : fator para limite inferior do gráfico s
#   índice 6 → B4  : fator para limite superior do gráfico s
#   índice 7 → c4  : fator de escala para estimar σ via s̄
CONSTANTES = {
    # n: (A2,   D3,    D4,    d2,    A3,    B3,    B4,    c4   )
    2:  (1.880, 0,     3.267, 1.128, 2.659, 0,     3.267, 0.7979),
    3:  (1.023, 0,     2.574, 1.693, 1.954, 0,     2.568, 0.8862),
    4:  (0.729, 0,     2.282, 2.059, 1.628, 0,     2.266, 0.9213),
    5:  (0.577, 0,     2.114, 2.326, 1.427, 0,     2.089, 0.9400),
    6:  (0.483, 0,     2.004, 2.534, 1.287, 0.030, 1.970, 0.9515),
    7:  (0.419, 0.076, 1.924, 2.704, 1.182, 0.118, 1.882, 0.9594),
    8:  (0.373, 0.136, 1.864, 2.847, 1.099, 0.185, 1.815, 0.9650),
    9:  (0.337, 0.184, 1.816, 2.970, 1.032, 0.239, 1.761, 0.9693),
    10: (0.308, 0.223, 1.777, 3.078, 0.975, 0.284, 1.716, 0.9727),
}


# ════════════════════════════════════════════════════════════
# FUNÇÕES AUXILIARES REUTILIZADAS POR TODAS AS QUESTÕES
# ════════════════════════════════════════════════════════════

def get_const(n, nome):
    """
    Retorna uma constante específica da tabela de controle.
    Parâmetros:
        n    : tamanho do subgrupo (ex.: 4, 5)
        nome : nome da constante como string ('A2','D3','D4','d2',
               'A3','B3','B4','c4')
    Retorna:
        valor float da constante correspondente
    """
    # mapeia o nome da constante para sua posição na tupla
    idx = {'A2':0,'D3':1,'D4':2,'d2':3,'A3':4,'B3':5,'B4':6,'c4':7}
    return CONSTANTES[n][idx[nome]]


def imprimir_limites(titulo, xbar_bar, R_bar_ou_s_bar, n, tipo='R'):
    """
    Calcula e exibe os limites de controle três sigma para os
    gráficos X̄ e R (ou X̄ e s).

    Para o gráfico X̄ com R:
        LSC = X̄̄ + A2·R̄        LIC = X̄̄ − A2·R̄
    Para o gráfico R:
        LSC = D4·R̄              LIC = D3·R̄
    Para o gráfico X̄ com s:
        LSC = X̄̄ + A3·s̄        LIC = X̄̄ − A3·s̄
    Para o gráfico s:
        LSC = B4·s̄              LIC = B3·s̄

    Parâmetros:
        titulo         : texto descritivo impresso no cabeçalho
        xbar_bar       : média das médias amostrais (X̄̄)
        R_bar_ou_s_bar : média das amplitudes (R̄) ou desvios-padrão (s̄)
        n              : tamanho do subgrupo
        tipo           : 'R' para gráfico de amplitudes,
                         's' para gráfico de desvios-padrão
    Retorna:
        tupla (limites_xbar, limites_R_ou_s) onde cada elemento é
        (LSC, LC, LIC)
    """
    print(f"\n{'='*55}")
    print(f"  {titulo}")
    print(f"{'='*55}")

    if tipo == 'R':
        # busca constantes para o gráfico X̄-R
        A2 = get_const(n,'A2')
        D3 = get_const(n,'D3')
        D4 = get_const(n,'D4')

        # calcula limites do gráfico X̄
        lsc_x = xbar_bar + A2 * R_bar_ou_s_bar   # limite superior de controle
        lc_x  = xbar_bar                           # linha central
        lic_x = xbar_bar - A2 * R_bar_ou_s_bar   # limite inferior de controle

        # calcula limites do gráfico R
        lsc_r = D4 * R_bar_ou_s_bar   # LSC do gráfico R
        lc_r  = R_bar_ou_s_bar        # linha central (R̄)
        lic_r = D3 * R_bar_ou_s_bar   # LIC do gráfico R (= 0 para n ≤ 6)

        print(f"  Gráfico X̄:  LSC={lsc_x:.4f}  LC={lc_x:.4f}  LIC={lic_x:.4f}")
        print(f"  Gráfico R:  LSC={lsc_r:.4f}  LC={lc_r:.4f}  LIC={lic_r:.4f}")
        return (lsc_x, lc_x, lic_x), (lsc_r, lc_r, lic_r)

    else:  # tipo == 's' — gráfico de desvios-padrão
        # busca constantes para o gráfico X̄-s
        A3 = get_const(n,'A3')
        B3 = get_const(n,'B3')
        B4 = get_const(n,'B4')

        # calcula limites do gráfico X̄ (usando s̄ em vez de R̄)
        lsc_x = xbar_bar + A3 * R_bar_ou_s_bar
        lc_x  = xbar_bar
        lic_x = xbar_bar - A3 * R_bar_ou_s_bar

        # calcula limites do gráfico s
        lsc_s = B4 * R_bar_ou_s_bar   # LSC do gráfico s
        lc_s  = R_bar_ou_s_bar        # linha central (s̄)
        lic_s = B3 * R_bar_ou_s_bar   # LIC do gráfico s

        print(f"  Gráfico X̄:  LSC={lsc_x:.4f}  LC={lc_x:.4f}  LIC={lic_x:.4f}")
        print(f"  Gráfico s:  LSC={lsc_s:.4f}  LC={lc_s:.4f}  LIC={lic_s:.4f}")
        return (lsc_x, lc_x, lic_x), (lsc_s, lc_s, lic_s)


def estimar_processo(xbar_bar, R_bar, n):
    """
    Estima a média (μ) e o desvio-padrão (σ) do processo
    a partir dos gráficos X̄-R, assumindo controle estatístico.

    Fórmulas:
        μ̂ = X̄̄       (melhor estimativa da média do processo)
        σ̂ = R̄ / d₂   (d₂ é o fator de escala para n dado)

    Parâmetros:
        xbar_bar : média das médias amostrais
        R_bar    : média das amplitudes
        n        : tamanho do subgrupo
    Retorna:
        (mu, sigma) como floats
    """
    d2 = get_const(n,'d2')   # fator que relaciona R̄ com σ
    mu    = xbar_bar          # estimativa da média do processo
    sigma = R_bar / d2        # estimativa do desvio-padrão do processo
    print(f"  Estimativas: μ̂ = {mu:.4f}   σ̂ = {sigma:.4f}")
    return mu, sigma


def estimar_processo_s(xbar_bar, s_bar, n):
    """
    Estima a média (μ) e o desvio-padrão (σ) do processo
    a partir dos gráficos X̄-s, assumindo controle estatístico.

    Fórmulas:
        μ̂ = X̄̄       (melhor estimativa da média do processo)
        σ̂ = s̄ / c₄   (c₄ é o fator de escala para n dado)

    Parâmetros:
        xbar_bar : média das médias amostrais
        s_bar    : média dos desvios-padrão amostrais
        n        : tamanho do subgrupo
    Retorna:
        (mu, sigma) como floats
    """
    c4 = get_const(n,'c4')   # fator que relaciona s̄ com σ
    mu    = xbar_bar          # estimativa da média do processo
    sigma = s_bar / c4        # estimativa do desvio-padrão do processo
    print(f"  Estimativas: μ̂ = {mu:.4f}   σ̂ = {sigma:.4f}")
    return mu, sigma


def prop_nao_conformes(mu, sigma, lsi=None, lss=None):
    """
    Calcula a proporção de itens não conformes supondo distribuição
    normal com média mu e desvio-padrão sigma.

    Usa a função de distribuição acumulada (CDF) da normal:
        P(X < LSI) = CDF(LSI, mu, sigma)   → itens abaixo do LSI
        P(X > LSS) = 1 − CDF(LSS, mu, sigma) → itens acima do LSS

    Parâmetros:
        mu    : média do processo
        sigma : desvio-padrão do processo
        lsi   : Limite Superior de Especificação inferior (None = sem LSI)
        lss   : Limite Superior de Especificação superior (None = sem LSS)
    Retorna:
        (p_abaixo, p_acima, p_total)
    """
    # proporção abaixo do LSI (retrabalho ou sucata por sub-especificação)
    p_abaixo = stats.norm.cdf(lsi, mu, sigma) if lsi is not None else 0
    # proporção acima do LSS (descarte por super-especificação)
    p_acima  = 1 - stats.norm.cdf(lss, mu, sigma) if lss is not None else 0
    # proporção total de não conformes
    p_total  = p_abaixo + p_acima

    print(f"  Proporção abaixo do LSI : {p_abaixo:.6f}  ({p_abaixo*100:.4f}%)")
    print(f"  Proporção acima  do LSS : {p_acima:.6f}  ({p_acima*100:.4f}%)")
    print(f"  Proporção total NC      : {p_total:.6f}  ({p_total*100:.4f}%)")
    return p_abaixo, p_acima, p_total


def Cp(sigma, lsi, lss):
    """
    Calcula a Razão de Capacidade do Processo (RCP) Cp.

    Fórmula:
        Cp = (LSS − LSI) / (6·σ)

    Interpretação:
        Cp ≥ 1.33 → processo capaz
        Cp ≥ 1.00 → processo marginalmente capaz
        Cp < 1.00 → processo incapaz de atender as especificações

    Parâmetros:
        sigma : desvio-padrão estimado do processo
        lsi   : limite de especificação inferior
        lss   : limite de especificação superior
    Retorna:
        cp (float)
    """
    cp = (lss - lsi) / (6 * sigma)   # razão entre a faixa de especificação e ±3σ
    print(f"  Cp = {cp:.4f}")
    return cp


def plot_xbar_R(xbars, Rs, limites_x, limites_r, titulo=''):
    """
    Plota o par de gráficos de controle X̄ e R em um único figure
    com dois subplots empilhados.

    Pontos fora dos limites são destacados com estrela vermelha (r*).

    Parâmetros:
        xbars     : lista/array das médias amostrais
        Rs        : lista/array das amplitudes amostrais
        limites_x : tupla (LSC, LC, LIC) do gráfico X̄
        limites_r : tupla (LSC, LC, LIC) do gráfico R
        titulo    : título geral do gráfico
    """
    fig, axes = plt.subplots(2, 1, figsize=(13, 6))  # dois subplots verticais
    fig.suptitle(titulo, fontsize=12, fontweight='bold')

    # números de amostra no eixo x (1, 2, 3, ...)
    ns = range(1, len(xbars) + 1)

    # itera pelos dois subplots: primeiro X̄, depois R
    for ax, dados, lims, ylabel in zip(
            axes,
            [xbars, Rs],
            [limites_x, limites_r],
            ['X̄', 'R']):

        # plota a série de dados em azul com pontos circulares
        ax.plot(ns, dados, 'b-o', ms=4)

        # linhas horizontais dos limites de controle
        ax.axhline(lims[0], color='r', ls='--', lw=1, label=f'LSC={lims[0]:.3f}')  # LSC em vermelho tracejado
        ax.axhline(lims[1], color='g', ls='-',  lw=1, label=f'LC={lims[1]:.3f}')   # LC em verde sólido
        ax.axhline(lims[2], color='r', ls='--', lw=1, label=f'LIC={lims[2]:.3f}')  # LIC em vermelho tracejado

        ax.set_ylabel(ylabel)                        # rótulo do eixo y
        ax.legend(loc='upper right', fontsize=8)     # legenda
        ax.set_xlabel('Amostra')                     # rótulo do eixo x

        # destaca pontos fora dos limites com estrela vermelha grande
        for i, v in enumerate(dados):
            if v > lims[0] or v < lims[2]:
                ax.plot(i + 1, v, 'r*', ms=12)

    plt.tight_layout()   # ajusta espaçamento entre subplots
    plt.show()           # exibe o gráfico


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.1 — Hastes de transmissão (n=4, 20 amostras)
# Dados fornecidos como somatórios: Σx̄ᵢ e ΣRᵢ
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.1 — Hastes de transmissão")
print("█"*60)

n61 = 4            # tamanho de cada subgrupo (4 diâmetros por amostra)
soma_xbar61 = 10.275   # somatório das 20 médias amostrais (Σx̄ᵢ)
soma_R61    = 1.012    # somatório das 20 amplitudes amostrais (ΣRᵢ)
m61 = 20               # número de amostras preliminares

# calcula a grande média (X̄̄) e a amplitude média (R̄)
xbar_bar61 = soma_xbar61 / m61   # X̄̄ = Σx̄ᵢ / m
R_bar61    = soma_R61    / m61   # R̄  = ΣRᵢ / m

print(f"\n(a) X̄̄ = {xbar_bar61:.4f}   R̄ = {R_bar61:.4f}")

# calcula e imprime os limites de controle três sigma
lx61, lr61 = imprimir_limites("6.1(a) — Limites X̄ e R", xbar_bar61, R_bar61, n61)

print("\n(b) Estimativas do processo (assumindo controle):")
# com o processo sob controle, estima μ e σ via R̄/d₂
mu61, sigma61 = estimar_processo(xbar_bar61, R_bar61, n61)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.2 — Lacres para óleo (n=5, 25 amostras)
# Dados em mm fornecidos como somatórios
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.2 — Lacres para óleo")
print("█"*60)

n62 = 5                 # tamanho do subgrupo
soma_xbar62 = 1253.75   # Σx̄ᵢ das 25 amostras (mm)
soma_R62    = 14.08     # ΣRᵢ das 25 amostras (mm)
m62 = 25                # número de amostras

# grande média e amplitude média
xbar_bar62 = soma_xbar62 / m62
R_bar62    = soma_R62    / m62

print(f"\n(a) X̄̄ = {xbar_bar62:.4f} mm   R̄ = {R_bar62:.4f} mm")

# limites de controle três sigma para X̄ e R
lx62, lr62 = imprimir_limites("6.2(a) — Limites X̄ e R", xbar_bar62, R_bar62, n62)

print("\n(b) Estimativas do processo:")
mu62, sigma62 = estimar_processo(xbar_bar62, R_bar62, n62)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.3 — Impacto de pontos fora de controle no gráfico R
# Questão teórica — resposta discursiva
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.3 — Discussão teórica")
print("█"*60)
# imprime a explicação conceitual sobre o impacto de pontos fora de
# controle no gráfico R sobre a confiabilidade dos limites do X̄
print("""
Se várias amostras preliminares mostram-se fora de controle no gráfico R,
os limites de controle calculados para o gráfico X̄ SÃO afetados, pois:

  • R̄ é usado para estimar σ (via σ̂ = R̄/d₂)
  • Os limites do X̄ são: X̄̄ ± A₂·R̄

Se o gráfico R estiver inflado por causas atribuíveis não identificadas,
R̄ será superestimado, gerando limites do X̄ artificialmente largos —
o que REDUZ a capacidade de detecção de deslocamentos na média.

Conclusão: os limites do X̄ NÃO são confiáveis até que o gráfico R
esteja sob controle. As amostras fora de controle devem ser investigadas,
a causa atribuível removida, e os limites recalculados sem essas amostras.
""")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.4 — Por que estabelecer controle no gráfico R primeiro?
# Questão teórica — resposta discursiva
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.4 — Discussão teórica")
print("█"*60)
# explica a lógica estatística de sequenciar a análise: R antes de X̄
print("""
O gráfico R controla a VARIABILIDADE do processo.
O gráfico X̄ controla a MÉDIA do processo.

Deve-se estabelecer o controle no gráfico R primeiro porque:

  1. Os limites do X̄ dependem de R̄ (usado para estimar σ).
  2. Se a variabilidade é instável, a estimativa de σ é não confiável,
     tornando os limites do X̄ sem significado estatístico.
  3. É impossível controlar a média de um processo cuja variabilidade
     está fora de controle — qualquer sinal no X̄ pode ser artefato
     da variabilidade instável.

Em resumo: controlar R antes garante que a base para os limites do X̄
seja sólida e que os sinais de fora de controle no X̄ sejam informativos.
""")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.5 — Tempo de admissão hospitalar (n=2, 20 subgrupos)
# Dados completos da Tabela 6E.1 — cada linha: subgrupo, x̄, R
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.5 — Admissão hospitalar")
print("█"*60)

# dicionário com os dados da tabela 6E.1 (tempo em minutos)
dados65 = {
    'subgrupo': list(range(1, 21)),
    'xbar': [8.3,8.1,7.9,6.3,8.5,7.5,8.0,7.4,6.4,7.5,
             8.8,9.1,5.9,9.0,6.4,7.3,5.3,7.6,8.1,8.0],   # médias por subgrupo
    'R':    [2,  3,  1,  5,  3,  4,  3,  2,  2,  4,
             3,  5,  3,  6,  3,  3,  2,  4,  3,  2]        # amplitudes por subgrupo
}
df65 = pd.DataFrame(dados65)   # converte para DataFrame para facilitar cálculos

n65 = 2   # cada subgrupo tem 2 pacientes
# calcula a grande média e a amplitude média diretamente do DataFrame
xbar_bar65 = df65['xbar'].mean()
R_bar65    = df65['R'].mean()

print(f"\n(a) X̄̄ = {xbar_bar65:.4f} min   R̄ = {R_bar65:.4f} min")
# calcula limites três sigma
lx65, lr65 = imprimir_limites("6.5(a) — Limites X̄ e R", xbar_bar65, R_bar65, n65)

# gera os gráficos de controle com os dados da tabela
plot_xbar_R(df65['xbar'], df65['R'], lx65, lr65, 'Q6.5 — Tempo de Admissão Hospitalar')

print("\n(b) Verificação de controle estatístico:")
# identifica quais amostras estão fora dos limites de controle
fora_x = (df65[df65['xbar'] > lx65[0]].index.tolist() +
          df65[df65['xbar'] < lx65[2]].index.tolist())
fora_r = (df65[df65['R'] > lr65[0]].index.tolist() +
          df65[df65['R'] < lr65[2]].index.tolist())
print(f"  Pontos fora de controle em X̄: {[i+1 for i in fora_x]}")
print(f"  Pontos fora de controle em R:  {[i+1 for i in fora_r]}")
if not fora_x and not fora_r:
    print("  → Processo aparentemente sob controle estatístico.")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.6 — Componentes de telefone celular (n=3)
# Parâmetros fornecidos diretamente (linha central conhecida)
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.6 — Componentes de celular")
print("█"*60)

n66 = 3                      # tamanho do subgrupo
xbar_bar66 = 0.3015          # linha central do gráfico X̄ (= X̄̄, em mm)
R_bar66    = 0.00154         # linha central do gráfico R (= R̄, em mm)
LSI66 = 0.295                # limite de especificação inferior (mm)
LSS66 = 0.305                # limite de especificação superior (mm)

print("\n(a) Estimativas do processo:")
# estima μ e σ a partir dos parâmetros dos gráficos de controle
mu66, sigma66 = estimar_processo(xbar_bar66, R_bar66, n66)

print("\n(b) Proporções de descarte (acima LSS) e retrabalho (abaixo LSI):")
# calcula proporção de itens fora das especificações
p_abaixo66, p_acima66, _ = prop_nao_conformes(mu66, sigma66, LSI66, LSS66)
print(f"  Retrabalho (< LSI): {p_abaixo66*100:.4f}%")
print(f"  Descarte   (> LSS): {p_acima66*100:.4f}%")

print("\n(c) Recentrando a média na nominal (0.30 mm):")
mu66c = 0.30   # nova média proposta (= ponto médio das especificações)
# recalcula as proporções com a média ajustada
p_abaixo66c, p_acima66c, _ = prop_nao_conformes(mu66c, sigma66, LSI66, LSS66)
print(f"  Retrabalho (< LSI): {p_abaixo66c*100:.4f}%")
print(f"  Descarte   (> LSS): {p_acima66c*100:.4f}%")
print(f"  → Recomenda-se ajustar a média para μ = 0.3000 mm (nominal)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.7 — Mancais (n=5, 24 amostras)
# Dados completos da Tabela 6E.2 — análise com revisão de limites
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.7 — Mancais")
print("█"*60)

# médias e amplitudes das 24 amostras (escala: últimas 3 casas decimais)
dados67_xbar = [34.5,34.2,31.6,31.5,35.0,34.1,32.6,33.8,34.8,33.6,
                31.9,38.6,35.4,34.0,37.1,34.9,33.5,31.7,34.0,35.1,
                33.7,32.8,33.5,34.2]
dados67_R    = [3,4,4,4,5,6,4,3,7,8,3,9,8,6,5,7,4,3,8,4,2,1,3,2]

df67 = pd.DataFrame({'xbar': dados67_xbar, 'R': dados67_R})
n67 = 5

# calcula grande média e amplitude média
xbar_bar67 = df67['xbar'].mean()
R_bar67    = df67['R'].mean()

# calcula limites tentativos (Fase I)
lx67, lr67 = imprimir_limites("6.7(a) — Limites X̄ e R (tentativo)", xbar_bar67, R_bar67, n67)
plot_xbar_R(df67['xbar'], df67['R'], lx67, lr67, 'Q6.7 — Mancais (tentativo)')

# identifica amostras fora de controle nos limites tentativos
fora_x67 = [i+1 for i,v in enumerate(df67['xbar']) if v > lx67[0] or v < lx67[2]]
fora_r67 = [i+1 for i,v in enumerate(df67['R'])    if v > lr67[0] or v < lr67[2]]
print(f"\n  Pontos fora em X̄: {fora_x67}")
print(f"  Pontos fora em R:  {fora_r67}")

if fora_x67 or fora_r67:
    # remove amostras fora de controle e recalcula (limites revisados)
    amostras_excluir = list(set(fora_x67 + fora_r67))
    print(f"\n  Excluindo amostras {amostras_excluir} e recalculando...")
    # drop usa índice zero-based, por isso subtrai 1
    df67r = df67.drop([i-1 for i in amostras_excluir]).reset_index(drop=True)
    xbar_bar67r = df67r['xbar'].mean()
    R_bar67r    = df67r['R'].mean()
    lx67r, lr67r = imprimir_limites("6.7(a) — Limites revisados", xbar_bar67r, R_bar67r, n67)
    mu67, sigma67 = estimar_processo(xbar_bar67r, R_bar67r, n67)
    plot_xbar_R(df67r['xbar'], df67r['R'], lx67r, lr67r, 'Q6.7 — Mancais (revisado)')
else:
    mu67, sigma67 = estimar_processo(xbar_bar67, R_bar67, n67)

print("\n(b) Capacidade — diâmetro 0.5030 ± 0.0010 (representado como 34 ± 10):")
# na escala codificada: 0.5020 → 30 e 0.5040 → 40
LSI67 = 30.0; LSS67 = 40.0
prop_nao_conformes(mu67, sigma67, LSI67, LSS67)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.8 — Fonte de alta voltagem (n=4, 20 amostras)
# Dados individuais da Tabela 6E.3 — calcula x̄ e R por amostra
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.8 — Fonte de alta voltagem")
print("█"*60)

# matriz 20×4: cada linha é uma amostra, cada coluna é uma medição
# os valores são xi = (voltagem_observada − 350) × 10
dados68 = np.array([
    [6,9,10,15],[10,4,6,11],[7,8,10,5],[8,9,6,13],[9,10,7,13],
    [12,11,10,10],[16,10,8,9],[7,5,10,4],[9,7,8,12],[15,16,10,13],
    [8,12,14,16],[6,13,9,11],[16,9,13,15],[7,13,10,12],[11,7,10,16],
    [15,10,11,14],[9,8,12,10],[15,7,10,11],[8,6,9,12],[13,14,11,15]
])

n68 = 4
# calcula média de cada linha (mean ao longo do eixo 1 = colunas)
xbars68 = dados68.mean(axis=1)
# calcula amplitude de cada linha (máximo − mínimo)
Rs68    = dados68.max(axis=1) - dados68.min(axis=1)

# grande média e amplitude média
xbar_bar68 = xbars68.mean()
R_bar68    = Rs68.mean()

print(f"\n  X̄̄ = {xbar_bar68:.4f}   R̄ = {R_bar68:.4f}")
lx68, lr68 = imprimir_limites("6.8(a) — Limites X̄ e R", xbar_bar68, R_bar68, n68)
plot_xbar_R(xbars68, Rs68, lx68, lr68, 'Q6.8 — Fonte de Alta Voltagem')

# lista amostras do X̄ fora dos limites
fora68 = [i+1 for i,v in enumerate(xbars68) if v > lx68[0] or v < lx68[2]]
print(f"  Pontos X̄ fora de controle: {fora68}")

mu68, sigma68 = estimar_processo(xbar_bar68, R_bar68, n68)

print("\n(b) Capacidade — especificações: 350 ± 5 V → xi = (V-350)×10, logo ±50:")
# na escala codificada: 350−5=345 → xi=−50 e 350+5=355 → xi=+50
LSI68 = -50.0; LSS68 = 50.0
p_ab68, p_ac68, p_t68 = prop_nao_conformes(mu68, sigma68, LSI68, LSS68)
Cp68 = Cp(sigma68, LSI68, LSS68)
print(f"  {'Processo CAPAZ' if Cp68 >= 1 else 'Processo NÃO CAPAZ'} (Cp={'≥' if Cp68>=1 else '<'}1)")

print("\n(c) Normalidade — verificação via Q-Q plot:")
fig, ax = plt.subplots(figsize=(6, 5))
# probplot gera os quantis teóricos x quantis observados e ajusta reta
(osm, osr), (slope, intercept, r) = stats.probplot(dados68.flatten(), dist='norm')
ax.plot(osm, osr, 'bo', ms=4)                                     # pontos observados
ax.plot(osm, slope*np.array(osm)+intercept, 'r-')                 # reta de referência normal
ax.set_title(f'Q6.8 — Q-Q Normal (R²={r**2:.4f})')
ax.set_xlabel('Quantis Teóricos')
ax.set_ylabel('Quantis Observados')
plt.tight_layout(); plt.show()
# R² próximo de 1 indica boa aderência à normalidade
print(f"  R² do Q-Q plot = {r**2:.4f} — {'suporte razoável' if r**2>0.98 else 'normalidade questionável'} à hipótese normal")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.9 — Orifícios em fibra de carbono (n=5, 20 amostras)
# Dados em décimos de milhar de polegada, relativos ao nominal
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.9 — Orifícios em fibra de carbono")
print("█"*60)

# matriz 20×5: cada linha é uma amostra de 5 medições
# valores são desvios do nominal (positivo = acima, negativo = abaixo)
dados69 = np.array([
    [-30,50,-20,10,30],[0,50,-60,-20,30],[-50,10,20,30,20],
    [-10,-10,30,-20,50],[20,-40,50,20,10],[0,0,40,-40,20],
    [0,0,20,-20,-10],[70,-30,30,-10,0],[0,0,20,-20,10],
    [10,20,30,10,50],[40,0,20,0,20],[30,20,30,10,40],
    [30,-30,0,10,10],[30,-10,50,-10,-30],[10,-10,50,40,0],
    [0,0,30,-10,0],[20,20,30,30,-20],[10,-20,50,30,10],
    [50,-10,40,20,0],[50,0,0,30,10]
])

n69 = 5
xbars69 = dados69.mean(axis=1)                        # média de cada amostra
Rs69    = dados69.max(axis=1) - dados69.min(axis=1)   # amplitude de cada amostra

xbar_bar69 = xbars69.mean()   # grande média
R_bar69    = Rs69.mean()      # amplitude média

print(f"\n  X̄̄ = {xbar_bar69:.4f}   R̄ = {R_bar69:.4f}")
lx69, lr69 = imprimir_limites("6.9(a) — Limites X̄ e R", xbar_bar69, R_bar69, n69)
plot_xbar_R(xbars69, Rs69, lx69, lr69, 'Q6.9 — Orifícios em Fibra de Carbono')

# verifica pontos fora dos limites
fora_x69 = [i+1 for i,v in enumerate(xbars69) if v > lx69[0] or v < lx69[2]]
fora_r69 = [i+1 for i,v in enumerate(Rs69)    if v > lr69[0] or v < lr69[2]]
print(f"  Pontos fora em X̄: {fora_x69}   em R: {fora_r69}")
print("  → Processo sob controle." if not fora_x69 and not fora_r69
      else "  → Investigar causas atribuíveis.")

print("\n(b) Desvio-padrão pelo método da amplitude:")
mu69, sigma69 = estimar_processo(xbar_bar69, R_bar69, n69)

print("\n(c) Capacidade — especificações: nominal ± 100:")
LSI69 = -100.0; LSS69 = 100.0   # faixa de ±100 em décimos de milhar de polegada
prop_nao_conformes(mu69, sigma69, LSI69, LSS69)
Cp69 = Cp(sigma69, LSI69, LSS69)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.10 — Placa de circuito impresso (n=3, 25 amostras)
# Dados completos da Tabela 6E.5 — espessura em polegadas
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.10 — Placa de Circuito Impresso")
print("█"*60)

# matriz 25×3: cada linha é uma amostra de 3 medições (polegadas)
dados610 = np.array([
    [0.0629,0.0636,0.0640],[0.0630,0.0631,0.0622],[0.0628,0.0631,0.0633],
    [0.0634,0.0630,0.0631],[0.0619,0.0628,0.0630],[0.0613,0.0629,0.0634],
    [0.0630,0.0639,0.0625],[0.0628,0.0627,0.0622],[0.0623,0.0626,0.0633],
    [0.0631,0.0631,0.0633],[0.0635,0.0630,0.0638],[0.0623,0.0630,0.0630],
    [0.0635,0.0631,0.0630],[0.0645,0.0640,0.0631],[0.0619,0.0644,0.0632],
    [0.0631,0.0627,0.0630],[0.0616,0.0623,0.0631],[0.0630,0.0630,0.0626],
    [0.0636,0.0631,0.0629],[0.0640,0.0635,0.0629],[0.0628,0.0625,0.0616],
    [0.0615,0.0625,0.0619],[0.0630,0.0632,0.0630],[0.0635,0.0629,0.0635],
    [0.0623,0.0629,0.0630]
])

n610 = 3
xbars610 = dados610.mean(axis=1)                        # médias amostrais
Rs610    = dados610.max(axis=1) - dados610.min(axis=1)  # amplitudes amostrais

xbar_bar610 = xbars610.mean()
R_bar610    = Rs610.mean()

print(f"\n  X̄̄ = {xbar_bar610:.6f} in   R̄ = {R_bar610:.6f} in")
lx610, lr610 = imprimir_limites("6.10(a) — Limites X̄ e R", xbar_bar610, R_bar610, n610)
plot_xbar_R(xbars610, Rs610, lx610, lr610, 'Q6.10 — Placa de Circuito Impresso')

fora_x610 = [i+1 for i,v in enumerate(xbars610) if v > lx610[0] or v < lx610[2]]
fora_r610 = [i+1 for i,v in enumerate(Rs610)    if v > lr610[0] or v < lr610[2]]
print(f"  Pontos fora em X̄: {fora_x610}   em R: {fora_r610}")

print("\n(b) Estimativa do desvio-padrão:")
mu610, sigma610 = estimar_processo(xbar_bar610, R_bar610, n610)

print("\n(c) Limites naturais de tolerância (μ ± 3σ):")
# os limites naturais representam a faixa que contém ~99.73% da produção
lnt_inf = mu610 - 3*sigma610
lnt_sup = mu610 + 3*sigma610
print(f"  LNT inferior = {lnt_inf:.6f}   LNT superior = {lnt_sup:.6f}")

print("\n(d) Capacidade — especificações 0.0630 in ± 0.0015 in:")
LSI610 = 0.0615; LSS610 = 0.0645
Cp610 = Cp(sigma610, LSI610, LSS610)
prop_nao_conformes(mu610, sigma610, LSI610, LSS610)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.11 — Garrafas de refrigerante (n=10, 15 amostras)
# Gráficos X̄-s e comparação com X̄-R
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.11 — Altura de preenchimento de garrafas")
print("█"*60)

# matriz 15×10: leituras de altura de preenchimento (0 = correto)
dados611 = np.array([
    [2.5,0.5,2.0,-1.0,1.0,-1.0,0.5,1.5,0.5,-1.5],
    [0.0,0.0,0.5,1.0,1.5,1.0,-1.0,1.0,1.5,-1.0],
    [1.5,1.0,1.0,-1.0,0.0,-1.5,-1.0,-1.0,1.0,-1.0],
    [0.0,0.5,-2.0,0.0,-1.0,1.5,-1.5,0.0,-2.0,-1.5],
    [0.0,0.0,0.0,-0.5,0.5,1.0,-0.5,-0.5,0.0,0.0],
    [1.0,-0.5,0.0,0.0,0.0,0.5,-1.0,1.0,-2.0,1.0],
    [1.0,-1.0,-1.0,-1.0,0.0,1.5,0.0,1.0,0.0,0.0],
    [0.0,-1.5,-0.5,1.5,0.0,0.0,0.0,-1.0,0.5,-0.5],
    [-2.0,-1.5,1.5,1.5,0.0,0.0,0.5,1.0,0.0,1.0],
    [-0.5,3.5,0.0,-1.0,-1.5,-1.5,-1.0,-1.0,1.0,0.5],
    [0.0,1.5,0.0,0.0,2.0,-1.5,0.5,-0.5,2.0,-1.0],
    [0.0,-2.0,-0.5,0.0,-0.5,2.0,1.5,0.0,0.5,-1.0],
    [-1.0,-0.5,-0.5,-1.0,0.0,0.5,0.5,-1.5,-1.0,-1.0],
    [0.5,1.0,-1.0,-0.5,-2.0,-1.0,-1.5,0.0,1.5,1.5],
    [1.0,0.0,1.5,1.5,1.0,-1.0,0.0,1.0,-2.0,-1.5]
])

n611 = 10
xbars611 = dados611.mean(axis=1)                        # médias de cada linha
ss611    = dados611.std(axis=1, ddof=1)                 # desvios-padrão amostrais (ddof=1 → divisão por n−1)
Rs611    = dados611.max(axis=1) - dados611.min(axis=1)  # amplitudes de cada linha

xbar_bar611 = xbars611.mean()   # grande média
s_bar611    = ss611.mean()      # média dos desvios-padrão
R_bar611    = Rs611.mean()      # média das amplitudes

print(f"\n  X̄̄ = {xbar_bar611:.4f}   s̄ = {s_bar611:.4f}   R̄ = {R_bar611:.4f}")

print("\n(a) Gráficos X̄ e s:")
# calcula limites usando gráfico s (mais eficiente para n=10)
lx611s, ls611 = imprimir_limites("6.11(a) — Limites X̄ e s", xbar_bar611, s_bar611, n611, tipo='s')

# plota X̄ e s em dois subplots
fig, axes = plt.subplots(2, 1, figsize=(13, 6))
fig.suptitle('Q6.11 — Preenchimento de Garrafas', fontsize=12, fontweight='bold')
for ax, dados, lims, ylabel in zip(axes,
        [xbars611, ss611], [lx611s, ls611], ['X̄','s']):
    ax.plot(range(1, 16), dados, 'b-o', ms=5)
    ax.axhline(lims[0], color='r', ls='--', lw=1, label=f'LSC={lims[0]:.3f}')
    ax.axhline(lims[1], color='g', ls='-',  lw=1, label=f'LC={lims[1]:.3f}')
    ax.axhline(lims[2], color='r', ls='--', lw=1, label=f'LIC={lims[2]:.3f}')
    ax.set_ylabel(ylabel); ax.legend(loc='upper right', fontsize=8)
plt.tight_layout(); plt.show()

print("\n(b) Comparação com gráfico R:")
# calcula os limites usando R para comparação com o gráfico s
lx611r, lr611 = imprimir_limites("6.11(b) — Limites X̄ e R", xbar_bar611, R_bar611, n611, tipo='R')
plot_xbar_R(xbars611, Rs611, lx611r, lr611, 'Q6.11(b) — Gráfico R comparativo')


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.12 — Alvejante em pó (n=5, 20 amostras)
# Dados completos da Tabela 6E.7 — peso em onças
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.12 — Peso de alvejante em pó")
print("█"*60)

# matriz 20×5: peso líquido (oz) de cada unidade amostrada
dados612 = np.array([
    [15.8,16.3,16.2,16.1,16.6],[16.3,15.9,15.9,16.2,16.4],
    [16.1,16.2,16.5,16.4,16.3],[16.3,16.2,15.9,16.4,16.2],
    [16.1,16.1,16.4,16.5,16.0],[16.1,15.8,16.7,16.6,16.4],
    [16.1,16.3,16.5,16.1,16.5],[16.2,16.1,16.2,16.1,16.3],
    [16.3,16.2,16.4,16.3,16.5],[16.6,16.3,16.4,16.1,16.5],
    [16.2,16.4,15.9,16.3,16.4],[15.9,16.6,16.7,16.2,16.5],
    [16.4,16.1,16.6,16.4,16.1],[16.5,16.3,16.2,16.3,16.4],
    [16.4,16.1,16.3,16.2,16.2],[16.0,16.2,16.3,16.3,16.2],
    [16.4,16.2,16.4,16.3,16.2],[16.0,16.2,16.4,16.5,16.1],
    [16.4,16.0,16.3,16.4,16.4],[16.4,16.4,16.5,16.0,15.8]
])

n612 = 5
xbars612 = dados612.mean(axis=1)                        # médias amostrais
Rs612    = dados612.max(axis=1) - dados612.min(axis=1)  # amplitudes amostrais

xbar_bar612 = xbars612.mean()
R_bar612    = Rs612.mean()

print(f"\n  X̄̄ = {xbar_bar612:.4f} oz   R̄ = {R_bar612:.4f} oz")
lx612, lr612 = imprimir_limites("6.12(a) — Limites X̄ e R", xbar_bar612, R_bar612, n612)
plot_xbar_R(xbars612, Rs612, lx612, lr612, 'Q6.12 — Peso de Alvejante em Pó')

# verifica pontos fora de controle
fora_x612 = [i+1 for i,v in enumerate(xbars612) if v > lx612[0] or v < lx612[2]]
fora_r612 = [i+1 for i,v in enumerate(Rs612)    if v > lr612[0] or v < lr612[2]]
print(f"  Pontos fora em X̄: {fora_x612}   em R: {fora_r612}")
print("  → Processo sob controle." if not fora_x612 and not fora_r612 else "  → Investigar.")

print("\n(b) Estimativas:")
mu612, sigma612 = estimar_processo(xbar_bar612, R_bar612, n612)

print("\n(c) Q-Q plot para verificação de normalidade:")
fig, ax = plt.subplots(figsize=(6, 5))
# aplana a matriz 20×5 em vetor de 100 valores para testar normalidade global
(osm, osr), (slope, intercept, r612) = stats.probplot(dados612.flatten(), dist='norm')
ax.plot(osm, osr, 'bo', ms=4)
ax.plot(osm, slope*np.array(osm)+intercept, 'r-')
ax.set_title(f'Q6.12 — Q-Q Normal (R²={r612**2:.4f})')
plt.tight_layout(); plt.show()
print(f"  R² = {r612**2:.4f}")

print("\n(d) Capacidade — especificações: 16.2 ± 0.5 oz:")
LSI612 = 15.7; LSS612 = 16.7   # limites de especificação inferior e superior
prop_nao_conformes(mu612, sigma612, LSI612, LSS612)
Cp612 = Cp(sigma612, LSI612, LSS612)

print("\n(e) Fração abaixo do LSI de 15.7 oz:")
# P(X < 15.7) = CDF normal avaliada em 15.7
p_abx612 = stats.norm.cdf(15.7, mu612, sigma612)
print(f"  P(X < 15.7) = {p_abx612:.6f}  ({p_abx612*100:.4f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.13 — Fonte de alta voltagem usando gráfico s
# Repete a Q6.8 mas com desvio-padrão amostral em vez de amplitude
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.13 — Fonte de alta voltagem (gráfico s)")
print("█"*60)

# calcula os desvios-padrão de cada linha do array de dados da Q6.8
ss68 = dados68.std(axis=1, ddof=1)   # ddof=1 → desvio amostral (n−1)
s_bar613 = ss68.mean()               # média dos desvios-padrão

print(f"\n  X̄̄ = {xbar_bar68:.4f}   s̄ = {s_bar613:.4f}")
lx613, ls613 = imprimir_limites("6.13 — Limites X̄ e s", xbar_bar68, s_bar613, n68, tipo='s')

# plota os dois gráficos lado a lado em subplots verticais
fig, axes = plt.subplots(2, 1, figsize=(13, 6))
fig.suptitle('Q6.13 — Fonte de Alta Voltagem (X̄ e s)', fontsize=12, fontweight='bold')
for ax, dados, lims, ylabel in zip(axes,
        [xbars68, ss68], [lx613, ls613], ['X̄','s']):
    ax.plot(range(1, 21), dados, 'b-o', ms=4)
    ax.axhline(lims[0], color='r', ls='--', lw=1, label=f'LSC={lims[0]:.3f}')
    ax.axhline(lims[1], color='g', ls='-',  lw=1, label=f'LC={lims[1]:.3f}')
    ax.axhline(lims[2], color='r', ls='--', lw=1, label=f'LIC={lims[2]:.3f}')
    ax.set_ylabel(ylabel); ax.legend(fontsize=8)
plt.tight_layout(); plt.show()


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.14 — Orifícios fibra de carbono usando gráfico s
# Repete a Q6.9 mas com desvio-padrão amostral em vez de amplitude
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.14 — Orifícios em fibra de carbono (gráfico s)")
print("█"*60)

# calcula os desvios-padrão de cada linha do array de dados da Q6.9
ss69 = dados69.std(axis=1, ddof=1)
s_bar614 = ss69.mean()

print(f"\n  X̄̄ = {xbar_bar69:.4f}   s̄ = {s_bar614:.4f}")
lx614, ls614 = imprimir_limites("6.14 — Limites X̄ e s", xbar_bar69, s_bar614, n69, tipo='s')

fig, axes = plt.subplots(2, 1, figsize=(13, 6))
fig.suptitle('Q6.14 — Orifícios Fibra de Carbono (X̄ e s)', fontsize=12, fontweight='bold')
for ax, dados, lims, ylabel in zip(axes,
        [xbars69, ss69], [lx614, ls614], ['X̄','s']):
    ax.plot(range(1, 21), dados, 'b-o', ms=4)
    ax.axhline(lims[0], color='r', ls='--', lw=1, label=f'LSC={lims[0]:.3f}')
    ax.axhline(lims[1], color='g', ls='-',  lw=1, label=f'LC={lims[1]:.3f}')
    ax.axhline(lims[2], color='r', ls='--', lw=1, label=f'LIC={lims[2]:.3f}')
    ax.set_ylabel(ylabel); ax.legend(fontsize=8)
plt.tight_layout(); plt.show()


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.15 — Anéis de pistão (n=5, 25 amostras)
# Especificações: 74.000 ± 0.05 mm
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.15 — Anéis de pistão")
print("█"*60)

# dados da Tabela 6.3 do livro (25 amostras × 5 observações, em mm)
dados615 = np.array([
    [74.030,74.002,74.019,73.992,74.008],
    [73.995,73.992,74.001,74.011,74.004],
    [73.988,74.024,74.021,74.005,74.002],
    [74.002,73.996,73.993,74.015,74.009],
    [73.992,74.007,74.015,73.989,74.014],
    [74.009,73.994,73.997,73.985,73.993],
    [73.995,74.006,73.994,74.000,74.005],
    [73.985,74.003,73.993,74.015,73.988],
    [74.008,73.995,74.009,74.005,74.004],
    [73.998,74.000,73.990,74.007,73.995],
    [73.994,73.998,73.994,73.995,73.990],
    [74.004,74.000,74.007,74.000,73.996],
    [73.983,74.002,73.998,73.997,74.012],
    [74.006,73.967,73.994,74.000,73.984],
    [74.012,74.014,73.998,73.999,74.007],
    [74.000,73.984,74.005,73.998,73.996],
    [73.994,74.012,73.986,74.005,74.007],
    [74.006,74.010,74.018,74.003,74.000],
    [73.984,74.002,74.003,74.005,73.997],
    [74.000,74.010,74.013,74.020,74.003],
    [73.982,74.001,74.015,74.005,73.996],
    [74.004,73.999,73.990,74.006,74.009],
    [74.010,73.989,73.990,74.009,74.014],
    [74.015,74.008,73.993,74.000,74.010],
    [73.982,73.984,73.995,74.017,74.013]
])

n615 = 5
xbars615 = dados615.mean(axis=1)
Rs615    = dados615.max(axis=1) - dados615.min(axis=1)

xbar_bar615 = xbars615.mean()
R_bar615    = Rs615.mean()

print(f"\n  X̄̄ = {xbar_bar615:.6f}   R̄ = {R_bar615:.6f}")
lx615, lr615 = imprimir_limites("6.15(a) — Limites X̄ e R", xbar_bar615, R_bar615, n615)
plot_xbar_R(xbars615, Rs615, lx615, lr615, 'Q6.15 — Anéis de Pistão')

mu615, sigma615 = estimar_processo(xbar_bar615, R_bar615, n615)

print("\n(c) Capacidade — especificações: 74.000 ± 0.05:")
LSI615 = 73.95; LSS615 = 74.05
prop_nao_conformes(mu615, sigma615, LSI615, LSS615)
Cp615 = Cp(sigma615, LSI615, LSS615)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.16 — Anéis de pistão — 15 novas amostras (Fase II)
# Plota as novas amostras nos limites estabelecidos na Q6.15
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.16 — Anéis de pistão — novas amostras")
print("█"*60)

# médias e amplitudes das 15 novas amostras da Tabela 6E.8
dados616_xbar = [74.009,74.002,73.992,74.004,73.997,
                 74.007,74.006,73.998,74.011,74.013,
                 74.004,74.017,74.020,74.023,74.013]
dados616_R    = [0.044,0.025,0.015,0.019,0.017,
                 0.026,0.023,0.014,0.025,0.030,
                 0.034,0.019,0.025,0.023,0.029]

print("\n  Plotando novas amostras nos limites de Q6.15:")
fig, axes = plt.subplots(2, 1, figsize=(13, 6))
fig.suptitle('Q6.16 — Anéis de Pistão — Novas Amostras', fontsize=12, fontweight='bold')

# concatena fase I (25 amostras) com fase II (15 novas) para plotagem contínua
all_xbar = list(xbars615) + dados616_xbar
all_R    = list(Rs615) + dados616_R

for ax, dados, lims, ylabel in zip(axes,
        [all_xbar, all_R], [lx615, lr615], ['X̄','R']):
    ax.plot(range(1, 26), dados[:25], 'b-o', ms=4, label='Fase I')          # Fase I em azul
    ax.plot(range(26, 41), dados[25:], 'g-o', ms=4, label='Fase II (novas)')# Fase II em verde
    ax.axhline(lims[0], color='r', ls='--', lw=1, label=f'LSC={lims[0]:.4f}')
    ax.axhline(lims[1], color='g', ls='-',  lw=1, label=f'LC={lims[1]:.4f}')
    ax.axhline(lims[2], color='r', ls='--', lw=1, label=f'LIC={lims[2]:.4f}')
    ax.axvline(25.5, color='k', ls=':', lw=1.5)   # linha vertical separando as fases
    ax.set_ylabel(ylabel); ax.legend(fontsize=7)
plt.tight_layout(); plt.show()

# verifica quais amostras da Fase II ultrapassam os limites da Fase I
fora_x616 = [i+26 for i,v in enumerate(dados616_xbar) if v > lx615[0] or v < lx615[2]]
fora_r616 = [i+26 for i,v in enumerate(dados616_R)    if v > lr615[0] or v < lr615[2]]
print(f"  Pontos fora em X̄ (novas amostras): {fora_x616}")
print(f"  Pontos fora em R  (novas amostras): {fora_r616}")
print("  → Processo permanece sob controle." if not fora_x616 and not fora_r616
      else "  → Sinal de fora de controle nas novas amostras!")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.17 — Torque do rolamento (parâmetros conhecidos)
# μ e σ fornecidos — calcula limites padrão para X̄ e s
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.17 — Torque do rolamento (parâmetros conhecidos)")
print("█"*60)

mu617    = 80      # média do processo (pol-lb) — valor de referência conhecido
sigma617 = 10      # desvio-padrão do processo — valor de referência conhecido
n617     = 10      # tamanho do subgrupo
c4_617   = get_const(n617, 'c4')   # fator c₄ para n=10
d2_617   = get_const(n617, 'd2')
D3_617   = get_const(n617, 'D3')
D4_617   = get_const(n617, 'D4')
A3_617   = get_const(n617, 'A3')
B3_617   = get_const(n617, 'B3')
B4_617   = get_const(n617, 'B4')

print(f"\n  Parâmetros: μ = {mu617}, σ = {sigma617}, n = {n617}")

# gráfico X̄ com parâmetros conhecidos: LC = μ, limites = μ ± 3σ/√n
print(f"\n  Gráfico X̄:")
print(f"    LSC = {mu617 + 3*sigma617/np.sqrt(n617):.4f}")
print(f"    LC  = {mu617:.4f}")
print(f"    LIC = {mu617 - 3*sigma617/np.sqrt(n617):.4f}")

# gráfico s com parâmetros conhecidos: LC = c₄·σ
s_esperado = c4_617 * sigma617   # valor esperado de s̄ quando o processo está sob controle
print(f"\n  Gráfico s (s̄ esperado = c₄·σ = {s_esperado:.4f}):")
print(f"    LSC = {B4_617 * s_esperado:.4f}")
print(f"    LC  = {s_esperado:.4f}")
print(f"    LIC = {B3_617 * s_esperado:.4f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.18 — Processo genérico (n=6, 50 amostras)
# Dados fornecidos como somatórios; análise completa com capacidade
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.18 — Processo genérico (n=6, 50 amostras)")
print("█"*60)

n618 = 6
soma_xbar618 = 2000.0   # Σx̄ᵢ das 50 amostras
soma_R618    = 200.0    # ΣRᵢ das 50 amostras
m618 = 50               # número de amostras

xbar_bar618 = soma_xbar618 / m618   # grande média
R_bar618    = soma_R618    / m618   # amplitude média

print(f"\n  X̄̄ = {xbar_bar618:.4f}   R̄ = {R_bar618:.4f}")

print("\n(a) Limites de controle:")
lx618, lr618 = imprimir_limites("6.18(a)", xbar_bar618, R_bar618, n618)
mu618, sigma618 = estimar_processo(xbar_bar618, R_bar618, n618)

print("\n(b) Limites naturais de tolerância (μ ± 3σ):")
# intervalo que contém ~99.73% da produção quando o processo é normal
print(f"  [{mu618 - 3*sigma618:.4f} , {mu618 + 3*sigma618:.4f}]")

print("\n(c) Especificações 41 ± 5.0:")
LSI618 = 36.0; LSS618 = 46.0
p_ab618, p_ac618, _ = prop_nao_conformes(mu618, sigma618, LSI618, LSS618)

print("\n(d) Sucata (abaixo LSI) e retrabalho (acima LSS):")
print(f"  Sucata:    {p_ab618*100:.4f}%")
print(f"  Retrabalho:{p_ac618*100:.4f}%")

print("\n(e) Sugestões de melhoria:")
print("  1. Reduzir a variabilidade do processo (σ menor)")
print("  2. Recentrar a média em 41 (ponto médio das especificações)")
print("  3. Investigar causas de variação por análise de causa-raiz (diagrama de Ishikawa)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.19 — Processo genérico (n=4, gráfico s)
# Somatório de s̄ fornecido; análise com gráfico X̄-s
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.19 — Processo genérico (n=4, gráfico s)")
print("█"*60)

n619 = 4
soma_xbar619 = 1000.0   # Σx̄ᵢ das 50 amostras
soma_s619    = 72.0     # Σsᵢ das 50 amostras
m619 = 50

xbar_bar619 = soma_xbar619 / m619   # grande média
s_bar619    = soma_s619    / m619   # média dos desvios-padrão amostrais

print(f"\n  X̄̄ = {xbar_bar619:.4f}   s̄ = {s_bar619:.4f}")

print("\n(a) Limites de controle:")
lx619, ls619 = imprimir_limites("6.19(a)", xbar_bar619, s_bar619, n619, tipo='s')
# estima σ via s̄/c₄ (mais eficiente que R̄/d₂ para qualquer n)
mu619, sigma619 = estimar_processo_s(xbar_bar619, s_bar619, n619)

print("\n(b) Limites naturais de tolerância:")
print(f"  [{mu619 - 3*sigma619:.4f} , {mu619 + 3*sigma619:.4f}]")

print("\n(c) Especificações 19 ± 4.0:")
LSI619 = 15.0; LSS619 = 23.0
p_ab619, p_ac619, _ = prop_nao_conformes(mu619, sigma619, LSI619, LSS619)

print("\n(d) Sucata/retrabalho:")
print(f"  Sucata (< LSI):    {p_ab619*100:.4f}%")
print(f"  Retrabalho (> LSS):{p_ac619*100:.4f}%")

print("\n(e) Se μ = 19.0 (nominal):")
# recalcula com a média centrada na especificação nominal
p_ab619e, p_ac619e, _ = prop_nao_conformes(19.0, sigma619, LSI619, LSS619)
total_antes = p_ab619 + p_ac619
total_depois = p_ab619e + p_ac619e
print(f"  Redução total de NC: {(total_antes-total_depois)*100:.4f}%")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.20 — Processo de usinagem (n=5, 20+10 amostras)
# Análise em duas fases com detecção de deslocamento
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.20 — Processo de usinagem")
print("█"*60)

# médias e amplitudes da Tabela 6E.9 (Fase I — 20 amostras)
dados620_xbar = [130.1,124.5,129.6,117.6,128.5,126.1,111.0,127.4,
                 143.5,133.6,134.6,146.7,132.4,138.1,128.7,127.6,
                 127.1,123.4,147.5,139.4]
dados620_R    = [27.9,57.0,39.1,30.0,42.7,43.0,36.1,46.0,
                 46.9,33.7,40.6,39.8,50.0,9.2,54.8,53.3,
                 42.9,53.2,38.3,32.2]

n620 = 5
xbar_bar620 = np.mean(dados620_xbar)   # grande média da Fase I
R_bar620    = np.mean(dados620_R)      # amplitude média da Fase I

print(f"\n  X̄̄ = {xbar_bar620:.4f}   R̄ = {R_bar620:.4f}")
lx620, lr620 = imprimir_limites("6.20(a)", xbar_bar620, R_bar620, n620)
plot_xbar_R(dados620_xbar, dados620_R, lx620, lr620, 'Q6.20 — Usinagem (Fase I)')

# novas amostras da Tabela 6E.10 (Fase II — 10 amostras)
novos620_xbar = [170.8,179.7,174.1,157.0,179.3,175.3,167.2,166.9,157.0,182.8]
novos620_R    = [81.8,24.0,48.0,26.9,60.8,37.8,51.0,44.2,44.5,53.0]

print("\n(b) Plotando novas amostras:")
fig, axes = plt.subplots(2, 1, figsize=(13, 6))
fig.suptitle('Q6.20(b) — Novas amostras', fontsize=12, fontweight='bold')

# concatena as duas fases para exibição contínua no mesmo gráfico
all_xbar620 = dados620_xbar + novos620_xbar
all_R620    = dados620_R    + novos620_R

for ax, dados, lims, ylabel in zip(axes,
        [all_xbar620, all_R620], [lx620, lr620], ['X̄','R']):
    ax.plot(range(1, 21), dados[:20], 'b-o', ms=4, label='Fase I')
    ax.plot(range(21, 31), dados[20:], 'r-o', ms=4, label='Fase II')
    ax.axhline(lims[0], color='r', ls='--', lw=1)
    ax.axhline(lims[1], color='g', ls='-',  lw=1)
    ax.axhline(lims[2], color='r', ls='--', lw=1)
    ax.axvline(20.5, color='k', ls=':', lw=1.5)   # separador entre fases
    ax.set_ylabel(ylabel); ax.legend(fontsize=8)
plt.tight_layout(); plt.show()

# identifica amostras da Fase II fora dos limites da Fase I
fora_x620b = [i+21 for i,v in enumerate(novos620_xbar) if v > lx620[0] or v < lx620[2]]
print(f"  Pontos fora em X̄ (Fase II): {fora_x620b}")
print("  → Processo SAIU de controle na Fase II (média deslocou para cima).")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.21 — Força de compressão — moldagem por injeção
# n=5, 20 amostras Fase I + 15 novas amostras Fase II
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.21 — Força de compressão (moldagem por injeção)")
print("█"*60)

# dados completos da Tabela 6E.12 (20 amostras × 5 observações, em psi)
dados621 = np.array([
    [83.0,81.2,78.7,75.7,77.0],[88.6,78.3,78.8,71.0,84.2],
    [85.7,75.8,84.3,75.2,81.0],[80.8,74.4,82.5,74.1,75.7],
    [83.4,78.4,82.6,78.2,78.9],[75.3,79.9,87.3,89.7,81.8],
    [74.5,78.0,80.8,73.4,79.7],[79.2,84.4,81.5,86.0,74.5],
    [80.5,86.2,76.2,64.1,80.2],[75.7,75.2,71.1,82.1,74.3],
    [80.0,81.5,78.4,73.8,78.1],[80.6,81.8,79.3,73.8,81.7],
    [82.7,81.3,79.1,82.0,79.5],[79.2,74.9,78.6,77.7,75.3],
    [85.5,82.1,82.8,73.4,71.7],[78.8,79.6,80.2,79.1,80.8],
    [82.1,78.2,75.5,78.2,82.1],[84.5,76.9,83.5,81.2,79.2],
    [79.0,77.8,81.2,84.4,81.6],[84.5,73.1,78.6,78.7,80.6]
])

n621 = 5
xbars621 = dados621.mean(axis=1)                        # médias por amostra
Rs621    = dados621.max(axis=1) - dados621.min(axis=1)  # amplitudes por amostra

xbar_bar621 = xbars621.mean()
R_bar621    = Rs621.mean()

print(f"\n  X̄̄ = {xbar_bar621:.4f} psi   R̄ = {R_bar621:.4f} psi")
lx621, lr621 = imprimir_limites("6.21(a) — Limites X̄ e R", xbar_bar621, R_bar621, n621)
plot_xbar_R(xbars621, Rs621, lx621, lr621, 'Q6.21 — Força de Compressão (Fase I)')

fora621 = [i+1 for i,v in enumerate(xbars621) if v > lx621[0] or v < lx621[2]]
print(f"  Pontos fora em X̄: {fora621}")
print("  → Processo sob controle na Fase I." if not fora621 else "  → Investigar.")

# novas amostras da Tabela 6E.13 (Fase II — 15 amostras)
novos621_xbar = [78.2,77.4,80.8,85.6,82.7,75.9,82.9,77.8,74.9,81.9,73.4,81.3,81.7,73.3,83.5]
novos621_R    = [12.6,15.7,6.8,17.5,22.5,21.3,27.9,14.6,11.0,14.0,24.9,10.9,27.6,19.9,22.2]

print("\n(b) Novas amostras:")
fig, axes = plt.subplots(2, 1, figsize=(14, 6))
fig.suptitle('Q6.21(b) — Força de Compressão — Novas Amostras', fontsize=12, fontweight='bold')
for ax, d_fase1, d_fase2, lims, ylabel in zip(axes,
        [list(xbars621), list(Rs621)],
        [novos621_xbar, novos621_R],
        [lx621, lr621], ['X̄','R']):
    ax.plot(range(1, 21), d_fase1, 'b-o', ms=4, label='Fase I')
    ax.plot(range(21, 36), d_fase2, 'r-o', ms=4, label='Fase II')
    ax.axhline(lims[0], color='r', ls='--', lw=1)
    ax.axhline(lims[1], color='g', ls='-',  lw=1)
    ax.axhline(lims[2], color='r', ls='--', lw=1)
    ax.axvline(20.5, color='k', ls=':', lw=1.5)   # marca início da Fase II
    ax.set_ylabel(ylabel); ax.legend(fontsize=8)
plt.tight_layout(); plt.show()

# identifica pontos fora nos limites estabelecidos na Fase I
fora621b_x = [i+21 for i,v in enumerate(novos621_xbar) if v > lx621[0] or v < lx621[2]]
fora621b_r = [i+21 for i,v in enumerate(novos621_R)    if v > lr621[0] or v < lr621[2]]
print(f"  Pontos fora em X̄: {fora621b_x}")
print(f"  Pontos fora em R:  {fora621b_r}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.25 — Gráfico X̄ e R (n=7, 35 amostras)
# Somatórios fornecidos; análise com capacidade
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.25 — Característica de qualidade (n=7)")
print("█"*60)

n625 = 7
soma_xbar625 = 7.805    # Σx̄ᵢ de 35 amostras
soma_R625    = 1.200    # ΣRᵢ de 35 amostras
m625 = 35

xbar_bar625 = soma_xbar625 / m625
R_bar625    = soma_R625    / m625

print(f"\n  X̄̄ = {xbar_bar625:.4f}   R̄ = {R_bar625:.4f}")
lx625, lr625 = imprimir_limites("6.25(a)", xbar_bar625, R_bar625, n625)
mu625, sigma625 = estimar_processo(xbar_bar625, R_bar625, n625)

print("\n(c) Especificações 220 ± 35:")
LSI625 = 185.0; LSS625 = 255.0
mu625_real = xbar_bar625
sigma625_real = sigma625
print(f"  μ̂ = {mu625_real:.4f}   σ̂ = {sigma625_real:.6f}")
print("  (Os valores são muito pequenos para as especificações 220±35 — unidades distintas)")
print("  Interpretação: X̄̄ = 7.805/35 ≈ 0.223. Possivelmente os dados estão em outra escala.")
print("  Supondo que os valores já representem a média/amplitude diretamente:")
print(f"  R̄ = {R_bar625:.4f} → σ̂ = R̄/d₂ = {sigma625:.6f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.26 — Processo de manufatura (n=5, 25 amostras)
# Somatórios fornecidos; análise com proporção de NC
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.26 — Processo de manufatura (n=5)")
print("█"*60)

n626 = 5
soma_xbar626 = 662.50   # Σx̄ᵢ de 25 amostras
soma_R626    = 9.00     # ΣRᵢ de 25 amostras
m626 = 25

xbar_bar626 = soma_xbar626 / m626
R_bar626    = soma_R626    / m626

print(f"\n  X̄̄ = {xbar_bar626:.4f}   R̄ = {R_bar626:.4f}")
lx626, lr626 = imprimir_limites("6.26(a)", xbar_bar626, R_bar626, n626)
mu626, sigma626 = estimar_processo(xbar_bar626, R_bar626, n626)

print("\n(b) Especificações 26.40 ± 0.50 (média estimada = 662.50/25 = 26.50):")
LSI626 = 25.90; LSS626 = 26.90
# usa 26.50 como estimativa da média real do processo
p_ab626, p_ac626, _ = prop_nao_conformes(26.50, sigma626, LSI626, LSS626)

print("\n(c) Se μ = 26.40 (nominal):")
# recalcula com a média ajustada para o nominal
p_ab626c, p_ac626c, _ = prop_nao_conformes(26.40, sigma626, LSI626, LSS626)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.27 — Processo de manufatura (n=5, gráfico s)
# Parâmetros X̄̄ e s̄ fornecidos; calcula risco β para deslocamento
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.27 — Processo de manufatura (n=5, s)")
print("█"*60)

n627 = 5
xbar_bar627 = 20.0   # grande média fornecida
s_bar627    = 1.5    # média dos desvios-padrão fornecida

print(f"\n  X̄̄ = {xbar_bar627}   s̄ = {s_bar627}")
# estima σ via s̄/c₄
mu627, sigma627 = estimar_processo_s(xbar_bar627, s_bar627, n627)

print("\n(a) Desvio-padrão estimado:", sigma627)
print("\n(b) Limites de controle:")
lx627, ls627 = imprimir_limites("6.27(b)", xbar_bar627, s_bar627, n627, tipo='s')

print("\n(c) Se μ se desloca para 22:")
# calcula quantos desvios-padrão de X̄ o deslocamento representa
delta627 = (22 - xbar_bar627) / (sigma627 / np.sqrt(n627))
# P(dentro dos limites com nova média) = P(LIC < X̄ < LSC | μ=22)
p_dentro627 = stats.norm.cdf(3 - delta627) - stats.norm.cdf(-3 - delta627)
p_fora627   = 1 - p_dentro627   # probabilidade de detectar o deslocamento
print(f"  δ = {delta627:.4f} desvios-padrão da X̄")
print(f"  P(dentro dos limites | μ=22) = β = {p_dentro627:.4f}")
print(f"  P(detectar deslocamento) = 1-β = {p_fora627:.4f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.28 — Processo genérico (n=3, 20 subgrupos)
# Análise com capacidade Seis Sigma
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.28 — Processo genérico (n=3)")
print("█"*60)

n628 = 3
soma_xbar628 = 5.502    # Σx̄ᵢ de 20 subgrupos
soma_R628    = 60.0     # ΣRᵢ de 20 subgrupos
m628 = 20

xbar_bar628 = soma_xbar628 / m628
R_bar628    = soma_R628    / m628

print(f"\n  X̄̄ = {xbar_bar628:.4f}   R̄ = {R_bar628:.4f}")
lx628, lr628 = imprimir_limites("6.28(a)", xbar_bar628, R_bar628, n628)
mu628, sigma628 = estimar_processo(xbar_bar628, R_bar628, n628)

print("\n(c) Especificações 275 ± 6:")
LSI628 = 269.0; LSS628 = 281.0
mu628_real = xbar_bar628
sigma628_real = sigma628
p_ab628, p_ac628, _ = prop_nao_conformes(mu628_real, sigma628_real, 269.0, 281.0)

print("\n(d) Redução para processo Seis Sigmas (Cp=2):")
# num processo Seis Sigma: LSS − LSI = 12σ → σ_necessário = (LSS−LSI)/12
sigma_6sigma628 = (LSS628 - LSI628) / 12
print(f"  σ necessário = {sigma_6sigma628:.4f}")
print(f"  σ atual      = {sigma628:.4f}")
print(f"  Redução necessária: {sigma628/sigma_6sigma628:.2f}× (σ deve ser dividido por {sigma628/sigma_6sigma628:.2f})")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.29 — Processo genérico (n=3, gráfico s)
# Análise via desvio-padrão; capacidade Seis Sigma
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.29 — Processo genérico (n=3, gráfico s)")
print("█"*60)

n629 = 3
soma_xbar629 = 55.45    # Σx̄ᵢ de 25 subgrupos
soma_s629    = 28.67    # Σsᵢ de 25 subgrupos
m629 = 25

xbar_bar629 = soma_xbar629 / m629
s_bar629    = soma_s629    / m629

print(f"\n  X̄̄ = {xbar_bar629:.4f}   s̄ = {s_bar629:.4f}")
lx629, ls629 = imprimir_limites("6.29(a)", xbar_bar629, s_bar629, n629, tipo='s')
mu629, sigma629 = estimar_processo_s(xbar_bar629, s_bar629, n629)

print("\n(c) Especificações 2.25 ± 4:")
LSI629 = -1.75; LSS629 = 6.25
p_ab629, p_ac629, _ = prop_nao_conformes(mu629, sigma629, LSI629, LSS629)

print("\n(d) Redução para Seis Sigmas:")
sigma_6sigma629 = (LSS629 - LSI629) / 12   # σ necessário para Cp = 2
print(f"  σ necessário = {sigma_6sigma629:.4f}")
print(f"  σ atual      = {sigma629:.4f}")
print(f"  Redução: σ deve ser reduzido por fator {sigma629/sigma_6sigma629:.2f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.30 — Probabilidade de detectar deslocamento
# Parâmetros do gráfico X̄ e nova média fornecidos
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.30 — Detecção de deslocamento (parâmetros conhecidos)")
print("█"*60)

sigma630 = 6.0    # desvio-padrão do processo (conhecido)
n630     = 4      # tamanho do subgrupo
LC630    = 200    # linha central do gráfico X̄
LSC630   = 209    # limite superior de controle
LIC630   = 191    # limite inferior de controle
mu_nova630 = 188  # nova média após o deslocamento

# desvio-padrão da distribuição de X̄ (erro-padrão da média)
sigma_xbar630 = sigma630 / np.sqrt(n630)

# probabilidade de X̄ cair fora dos limites dado que μ = 188
p_fora630 = (1 - stats.norm.cdf(LSC630, mu_nova630, sigma_xbar630) +
             stats.norm.cdf(LIC630, mu_nova630, sigma_xbar630))

print(f"\n  σ_X̄ = {sigma_xbar630:.4f}")
print(f"  P(detectar deslocamento para 188 na 1ª amostra) = {p_fora630:.4f} ({p_fora630*100:.2f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.31 — Peça forjada (capacidade e ajuste de média)
# Análise se ajuste da ferramenta resolve o problema de capacidade
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.31 — Peça forjada")
print("█"*60)

xbar_bar631 = 104.0   # grande média atual do processo
R_bar631    = 9.30    # amplitude média atual
n631 = 5              # tamanho do subgrupo
LSI631 = 90.0         # especificação inferior (100 − 10)
LSS631 = 110.0        # especificação superior (100 + 10)

# estima σ pelo método da amplitude
mu631, sigma631 = estimar_processo(xbar_bar631, R_bar631, n631)
print(f"\n  Especificações: 100 ± 10")
print(f"  μ̂ = {mu631:.4f}   σ̂ = {sigma631:.4f}")

print(f"\n  Com μ ajustada para 100 (ponto nominal):")
# verifica proporção de NC com a média centrada em 100
p_ab631, p_ac631, _ = prop_nao_conformes(100.0, sigma631, LSI631, LSS631)
Cp631 = Cp(sigma631, LSI631, LSS631)
print(f"  → Sim, é possível ajustar a média para 100 via ajuste de ferramenta.")

print(f"\n  Capacidade atual (μ = 104):")
# calcula NC com a média atual deslocada (= 104 em vez de 100)
p_ab631b, p_ac631b, _ = prop_nao_conformes(mu631, sigma631, LSI631, LSS631)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.32 — Parâmetros conhecidos μ=10, σ=2.5, n=2
# Calcula limites para X̄, R e s com parâmetros de referência
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.32 — Gráficos com parâmetros conhecidos (n=2)")
print("█"*60)

mu632 = 10.0; sigma632 = 2.5; n632 = 2   # parâmetros de referência
# busca todas as constantes necessárias para n=2
d2_632 = get_const(n632,'d2'); D3_632 = get_const(n632,'D3'); D4_632 = get_const(n632,'D4')
c4_632 = get_const(n632,'c4'); B3_632 = get_const(n632,'B3'); B4_632 = get_const(n632,'B4')

# valores esperados de R e s quando o processo está sob controle
R_esperado632 = d2_632 * sigma632   # E(R) = d₂·σ
s_esperado632 = c4_632 * sigma632   # E(s) = c₄·σ

print(f"\n(a) Gráfico X̄:")
# limites = μ ± 3·(σ/√n) = μ ± 3·σ_X̄
print(f"    LSC = {mu632 + 3*sigma632/np.sqrt(n632):.4f}")
print(f"    LC  = {mu632:.4f}")
print(f"    LIC = {mu632 - 3*sigma632/np.sqrt(n632):.4f}")

print(f"\n(b) Gráfico R (R̄ esperado = d₂·σ = {R_esperado632:.4f}):")
# LSC = D₄·R̄   LIC = D₃·R̄
print(f"    LSC = {D4_632 * R_esperado632:.4f}")
print(f"    LC  = {R_esperado632:.4f}")
print(f"    LIC = {D3_632 * R_esperado632:.4f}")

print(f"\n(c) Gráfico s (s̄ esperado = c₄·σ = {s_esperado632:.4f}):")
# LSC = B₄·s̄   LIC = B₃·s̄
print(f"    LSC = {B4_632 * s_esperado632:.4f}")
print(f"    LC  = {s_esperado632:.4f}")
print(f"    LIC = {B3_632 * s_esperado632:.4f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.33 — n=5, X̄̄=20, R̄=4.56
# Limites, capacidade e probabilidade de não detectar deslocamento
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.33 — Processo (n=5, X̄̄=20, R̄=4.56)")
print("█"*60)

n633 = 5; xbar_bar633 = 20.0; R_bar633 = 4.56
lx633, lr633 = imprimir_limites("6.33(a)", xbar_bar633, R_bar633, n633)
mu633, sigma633 = estimar_processo(xbar_bar633, R_bar633, n633)

print("\n(c) Especificações 19 ± 5:")
LSI633 = 14.0; LSS633 = 24.0
prop_nao_conformes(mu633, sigma633, LSI633, LSS633)
Cp633 = Cp(sigma633, LSI633, LSS633)

print("\n(d) Se μ se desloca para 24:")
# σ_X̄ = σ/√n: desvio-padrão da distribuição amostral de X̄
sigma_xbar633 = sigma633 / np.sqrt(n633)
LSC633_x = lx633[0]; LIC633_x = lx633[2]
# β = P(LIC < X̄ < LSC | μ=24) — probabilidade de não detectar o deslocamento
beta633 = (stats.norm.cdf(LSC633_x, 24, sigma_xbar633) -
           stats.norm.cdf(LIC633_x, 24, sigma_xbar633))
print(f"  P(não detectar na 1ª amostra) = β = {beta633:.4f} ({beta633*100:.2f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.38 — Força de resistência (n=6, 30 amostras)
# Análise completa com risco β
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.38 — Força de resistência (n=6)")
print("█"*60)

n638 = 6
soma_xbar638 = 6000.0   # Σx̄ᵢ de 30 amostras
soma_R638    = 150.0    # ΣRᵢ de 30 amostras
m638 = 30

xbar_bar638 = soma_xbar638 / m638
R_bar638    = soma_R638    / m638

print(f"\n  X̄̄ = {xbar_bar638:.4f}   R̄ = {R_bar638:.4f}")
lx638, lr638 = imprimir_limites("6.38(a)", xbar_bar638, R_bar638, n638)
mu638, sigma638 = estimar_processo(xbar_bar638, R_bar638, n638)

print("\n(b) Especificações 200 ± 5:")
LSI638 = 195.0; LSS638 = 205.0
p_ab638, p_ac638, _ = prop_nao_conformes(mu638, sigma638, LSI638, LSS638)
Cp638 = Cp(sigma638, LSI638, LSS638)

print("\n(c) Risco β quando μ verdadeira = 199:")
# σ_X̄ = σ/√n (erro padrão da distribuição amostral)
sigma_xbar638 = sigma638 / np.sqrt(n638)
# β = P(processo parece sob controle | μ deslocou para 199)
beta638 = (stats.norm.cdf(lx638[0], 199, sigma_xbar638) -
           stats.norm.cdf(lx638[2], 199, sigma_xbar638))
print(f"  β = P(não detectar | μ=199) = {beta638:.4f} ({beta638*100:.2f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.39 — Detecção de deslocamento (σ conhecido)
# Calcula P(detectar) na 1ª amostra após deslocamento 100→92
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.39 — Detecção de deslocamento σ conhecido")
print("█"*60)

LC639 = 100; sigma639 = 6; n639 = 4; mu_nova639 = 92
# desvio-padrão da X̄ = σ/√n
sigma_xbar639 = sigma639 / np.sqrt(n639)
# limites do gráfico X̄ baseados em σ conhecido
LSC639 = LC639 + 3*sigma_xbar639
LIC639 = LC639 - 3*sigma_xbar639

# probabilidade de X̄ cair fora dos limites com a nova média μ=92
p_detec639 = (1 - stats.norm.cdf(LSC639, mu_nova639, sigma_xbar639) +
              stats.norm.cdf(LIC639, mu_nova639, sigma_xbar639))
print(f"\n  LSC = {LSC639:.4f}   LC = {LC639}   LIC = {LIC639:.4f}")
print(f"  P(detectar deslocamento 100→92 na 1ª amostra) = {p_detec639:.4f} ({p_detec639*100:.2f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.40 — Fonte de energia (n=5, 20 amostras)
# Dados da Tabela 6E.17; análise completa com sugestões
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.40 — Fonte de energia (n=5)")
print("█"*60)

# médias e amplitudes da Tabela 6E.17
dados640_xbar = [103,102,104,105,104,106,102,105,106,104,
                 105,103,102,105,104,105,106,102,105,103]
dados640_R    = [4,5,2,11,4,3,7,2,4,3,4,2,3,4,5,3,5,2,4,2]

n640 = 5
xbar_bar640 = np.mean(dados640_xbar)   # grande média
R_bar640    = np.mean(dados640_R)      # amplitude média

print(f"\n  X̄̄ = {xbar_bar640:.4f}   R̄ = {R_bar640:.4f}")
lx640, lr640 = imprimir_limites("6.40(a)", xbar_bar640, R_bar640, n640)
plot_xbar_R(dados640_xbar, dados640_R, lx640, lr640, 'Q6.40 — Fonte de Energia')

# verifica quais amostras do X̄ estão fora dos limites
fora640 = [i+1 for i,v in enumerate(dados640_xbar) if v > lx640[0] or v < lx640[2]]
print(f"  Pontos fora em X̄: {fora640}")

mu640, sigma640 = estimar_processo(xbar_bar640, R_bar640, n640)

print("\n(c) Limites naturais de tolerância:")
# intervalo μ ± 3σ contém ~99.73% da produção
print(f"  [{mu640 - 3*sigma640:.4f} , {mu640 + 3*sigma640:.4f}]")

print("\n(d) Especificações 103 ± 4:")
LSI640 = 99.0; LSS640 = 107.0
p_ab640, p_ac640, _ = prop_nao_conformes(mu640, sigma640, LSI640, LSS640)

print("\n(e) Sugestões:")
print("  1. Recentrar a média em 103 (nominal) — atualmente X̄̄ = 104")
print("  2. Reduzir variabilidade (R̄ elevado indica alta amplitude)")
print("  3. Investigar amostra 4 (R=11) como potencial causa atribuível")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.41 — Força de resistência de fio (n=5, 30 amostras)
# Único LSI; calcula fração abaixo da especificação
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.41 — Força de resistência de fio")
print("█"*60)

n641 = 5
soma_xbar641 = 607.8    # Σx̄ᵢ de 30 amostras (em libras)
soma_R641    = 144.0    # ΣRᵢ de 30 amostras (em libras)
m641 = 30

xbar_bar641 = soma_xbar641 / m641
R_bar641    = soma_R641    / m641

print(f"\n  X̄̄ = {xbar_bar641:.4f} lb   R̄ = {R_bar641:.4f} lb")
lx641, lr641 = imprimir_limites("6.41(a)", xbar_bar641, R_bar641, n641)
mu641, sigma641 = estimar_processo(xbar_bar641, R_bar641, n641)

print("\n(b) LSI único = 16 lb:")
# calcula P(X < 16 lb) usando a CDF da normal
p_abaixo641 = stats.norm.cdf(16.0, mu641, sigma641)
print(f"  P(X < 16 lb) = {p_abaixo641:.6f} ({p_abaixo641*100:.4f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.45 — Ferrolho metálico (n=6, 30 amostras)
# Análise completa com otimização da média para minimizar NC
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.45 — Ferrolho metálico (n=6)")
print("█"*60)

n645 = 6
soma_xbar645 = 12870.0   # Σx̄ᵢ de 30 amostras
soma_R645    = 1350.0    # ΣRᵢ de 30 amostras
m645 = 30

xbar_bar645 = soma_xbar645 / m645
R_bar645    = soma_R645    / m645

print(f"\n  X̄̄ = {xbar_bar645:.4f}   R̄ = {R_bar645:.4f}")
lx645, lr645 = imprimir_limites("6.45(a)", xbar_bar645, R_bar645, n645)
mu645, sigma645 = estimar_processo(xbar_bar645, R_bar645, n645)

LSI645 = 400.0; LSS645 = 480.0
print("\n(c) Especificações 440 ± 40:")
p_ab645, p_ac645, _ = prop_nao_conformes(mu645, sigma645, LSI645, LSS645)

print("\n(d) Para minimizar NC, centrar a média:")
# a média ótima é o ponto médio das especificações
print(f"  μ_ótima = (LSI + LSS)/2 = {(LSI645+LSS645)/2:.1f}")
p_ab645d, p_ac645d, _ = prop_nao_conformes((LSI645+LSS645)/2, sigma645, LSI645, LSS645)


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.47 — Limites dois sigma e de probabilidade
# Gráfico X̄ com μ=100, σ=8, n=4
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.47 — Limites dois sigma e probabilidade")
print("█"*60)

mu647 = 100; sigma647 = 8; n647 = 4
# erro padrão da X̄
sigma_xbar647 = sigma647 / np.sqrt(n647)

print(f"\n  σ_X̄ = {sigma_xbar647:.4f}")

print(f"\n(a) Limites dois sigma (k=2 em vez de k=3):")
# limites k=2: μ ± 2·σ_X̄  (maior taxa de alarme falso)
print(f"    LSC = {mu647 + 2*sigma_xbar647:.4f}")
print(f"    LC  = {mu647:.4f}")
print(f"    LIC = {mu647 - 2*sigma_xbar647:.4f}")

# quantil z para α/2 = 0.005/2 = 0.0025 (bilateral)
z647 = stats.norm.ppf(1 - 0.005/2)
print(f"\n(b) Limites de probabilidade 0.005 (α=0.005, dois lados):")
print(f"    z_α/2 = {z647:.4f}")
print(f"    LSC = {mu647 + z647*sigma_xbar647:.4f}")
print(f"    LIC = {mu647 - z647*sigma_xbar647:.4f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.48 — Probabilidade de sinal até o 3º ponto
# Gráfico X̄ com parâmetros conhecidos e média deslocada
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.48 — Probabilidade de sinal até 3ª amostra")
print("█"*60)

LSC648 = 104; LC648 = 100; LIC648 = 96; n648 = 5
mu_vera648 = 98    # média verdadeira do processo (deslocada de 100 para 98)
sigma648_vera = 8  # desvio-padrão verdadeiro do processo
sigma_xbar648 = sigma648_vera / np.sqrt(n648)

# probabilidade de um ponto de X̄ cair fora dos limites dado μ=98
p_sinal648 = (1 - stats.norm.cdf(LSC648, mu_vera648, sigma_xbar648) +
              stats.norm.cdf(LIC648, mu_vera648, sigma_xbar648))
print(f"\n  P(sinal em 1 amostra) = {p_sinal648:.4f}")

# probabilidade de pelo menos 1 sinal nos primeiros 3 pontos
# = 1 − P(nenhum sinal em 3 amostras independentes) = 1 − (1−p)³
p_pelo_menos1_648 = 1 - (1 - p_sinal648)**3
print(f"  P(pelo menos 1 sinal nos 3 primeiros pontos) = {p_pelo_menos1_648:.4f} ({p_pelo_menos1_648*100:.2f}%)")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.50 — Capacidade do processo (gráfico X̄-s, n=4)
# Parâmetros dos gráficos fornecidos; verifica capacidade
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.50 — Capacidade do processo (gráfico X̄ e s, n=4)")
print("█"*60)

# parâmetros dos gráficos fornecidos no enunciado
LSC650_x = 201.88; LC650_x = 200.00; LIC650_x = 198.12
LSC650_s = 2.266;  LC650_s = 1.000;  LIC650_s = 0
n650 = 4
c4_650 = get_const(n650, 'c4')   # fator c₄ para n=4

mu650    = LC650_x             # média estimada = linha central do X̄
sigma650 = LC650_s / c4_650   # σ̂ = s̄/c₄ (usando a linha central do gráfico s)

print(f"\n  μ̂ = {mu650:.4f}   σ̂ = {sigma650:.4f}")
print(f"  Especificações: 197.50 e 202.50")
LSI650 = 197.50; LSS650 = 202.50
p_ab650, p_ac650, p_t650 = prop_nao_conformes(mu650, sigma650, LSI650, LSS650)
Cp650 = Cp(sigma650, LSI650, LSS650)

# limites naturais de tolerância μ ± 3σ
lnt_inf650 = mu650 - 3*sigma650
lnt_sup650 = mu650 + 3*sigma650
print(f"\n  Limites naturais de tolerância: [{lnt_inf650:.4f} , {lnt_sup650:.4f}]")
print(f"  Especificações fora dos LNT? {'SIM' if LSI650 > lnt_inf650 or LSS650 < lnt_sup650 else 'NÃO'}")
print(f"  → Processo {'CAPAZ' if Cp650 >= 1 else 'NÃO CAPAZ'} (Cp = {Cp650:.4f})")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.53 — Processo (n=7, 30 amostras)
# Somatórios fornecidos; calcula limites X̄-R e equivalência X̄-s
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.53 — Processo (n=7, 30 amostras)")
print("█"*60)

n653 = 7
soma_xbar653 = 2700.0   # Σx̄ᵢ de 30 amostras
soma_R653    = 120.0    # ΣRᵢ de 30 amostras
m653 = 30

xbar_bar653 = soma_xbar653 / m653
R_bar653    = soma_R653    / m653

print(f"\n  X̄̄ = {xbar_bar653:.4f}   R̄ = {R_bar653:.4f}")
lx653, lr653 = imprimir_limites("6.53(a)", xbar_bar653, R_bar653, n653)
mu653, sigma653 = estimar_processo(xbar_bar653, R_bar653, n653)

print("\n(c) Limites para gráfico s:")
# converte R̄ → s̄ usando: s̄ = c₄·σ e σ = R̄/d₂ → s̄ = c₄·R̄/d₂
s_bar653 = get_const(n653,'c4') * sigma653
lx653s, ls653 = imprimir_limites("6.53(c) — s", xbar_bar653, s_bar653, n653, tipo='s')


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.55 — Detecção de deslocamento e CMS
# Parâmetros do gráfico X̄ dados; calcula P(detectar) e CMS₁
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.55 — Detecção de deslocamento (n=4)")
print("█"*60)

LSC655 = 815; LC655 = 800; LIC655 = 785; n655 = 4

# recupera σ a partir dos limites: LSC − LC = 3·σ/√n → σ = (LSC−LC)·√n/3
sigma655 = (LSC655 - LC655) * np.sqrt(n655) / 3
sigma_xbar655 = sigma655 / np.sqrt(n655)   # erro padrão de X̄
mu_nova655 = 790   # nova média após o deslocamento

# P(X̄ fora dos limites | μ = 790)
p_detec655 = (1 - stats.norm.cdf(LSC655, mu_nova655, sigma_xbar655) +
              stats.norm.cdf(LIC655, mu_nova655, sigma_xbar655))
beta655 = 1 - p_detec655     # risco β = P(não detectar)
CMS655 = 1 / p_detec655      # CMS = comprimento médio da sequência = 1/P(detectar)

print(f"\n  σ = {sigma655:.4f}   σ_X̄ = {sigma_xbar655:.4f}")
print(f"  P(detectar deslocamento 800→790 na 1ª amostra) = {p_detec655:.4f}")
print(f"  β = {beta655:.4f}")
print(f"\n  CMS₁ (comprimento médio da sequência) = {CMS655:.2f} amostras")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.57 — Risco α, capacidade e deslocamento (n=9)
# Parâmetros fornecidos; análise completa
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.57 — Risco α, capacidade e detecção")
print("█"*60)

LSC657 = 363.0; LC657 = 360.0; LIC657 = 357.0; n657 = 9

# recupera σ a partir dos limites: (LSC − LC) = 3·σ_X̄ = 3·σ/√n
sigma657 = (LSC657 - LC657) * np.sqrt(n657) / 3
sigma_xbar657 = sigma657 / np.sqrt(n657)

# risco α = P(X̄ fora dos limites | processo sob controle, μ = LC)
# usa simetria: α = 2·P(X̄ > LSC | μ = LC)
alpha657 = 2 * (1 - stats.norm.cdf(LSC657, LC657, sigma_xbar657))
print(f"\n  σ = {sigma657:.4f}   σ_X̄ = {sigma_xbar657:.4f}")
print(f"\n(a) Risco α = {alpha657:.6f} ({alpha657*100:.4f}%)")

print("\n(b) Especificações 358 ± 6:")
LSI657 = 352.0; LSS657 = 364.0
p_ab657, p_ac657, _ = prop_nao_conformes(LC657, sigma657, LSI657, LSS657)
Cp657 = Cp(sigma657, LSI657, LSS657)

print("\n(c) Se μ desloca para 357:")
mu_nova657 = 357.0
# β = P(processo parece sob controle com nova média de 357)
beta657c = (stats.norm.cdf(LSC657, mu_nova657, sigma_xbar657) -
            stats.norm.cdf(LIC657, mu_nova657, sigma_xbar657))
print(f"  β = P(não detectar | μ=357) = {beta657c:.4f}")

print("\n(d) Limites para α = 0.01 (mais restritivo que os três sigma):")
# z_α/2 para α=0.01 (bilateral): z = invnorm(1 − 0.01/2)
z_alpha_657 = stats.norm.ppf(1 - 0.01/2)
print(f"  z_α/2 = {z_alpha_657:.4f}")
print(f"  LSC = {LC657 + z_alpha_657 * sigma_xbar657:.4f}")
print(f"  LIC = {LC657 - z_alpha_657 * sigma_xbar657:.4f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.58 — Gráfico X̄ e R (n=4, parâmetros dados)
# Análise completa: σ, gráfico s equivalente, capacidade, detecção
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.58 — Processo (n=4, parâmetros dados)")
print("█"*60)

# parâmetros fornecidos nos dois gráficos
LSC658_x = 626.0; LC658_x = 620.0; LIC658_x = 614.0
LSC658_r = 18.795; LC658_r = 8.236; LIC658_r = 0.0
n658 = 4

# estima σ via gráfico R: R̄ = d₂·σ → σ = R̄/d₂
d2_658 = get_const(n658, 'd2')
sigma658 = LC658_r / d2_658    # σ̂ do processo
mu658    = LC658_x             # μ̂ = linha central do X̄

# constantes para o gráfico s equivalente
c4_658 = get_const(n658, 'c4')
B3_658 = get_const(n658, 'B3')
B4_658 = get_const(n658, 'B4')

print(f"\n(a) σ̂ = R̄/d₂ = {LC658_r}/{d2_658} = {sigma658:.4f}")

# s̄ equivalente: s̄ = c₄·σ
s_bar658 = c4_658 * sigma658
print(f"\n(b) Parâmetros gráfico s (s̄ = c₄·σ = {s_bar658:.4f}):")
print(f"    LSC = {B4_658 * s_bar658:.4f}")
print(f"    LC  = {s_bar658:.4f}")
print(f"    LIC = {B3_658 * s_bar658:.4f}")

print("\n(c) Especificações 610 ± 15:")
LSI658 = 595.0; LSS658 = 625.0
p_ab658, p_ac658, _ = prop_nao_conformes(mu658, sigma658, LSI658, LSS658)
Cp658 = Cp(sigma658, LSI658, LSS658)

print("\n(e) Se μ desloca para 610:")
mu_nova658 = 610.0
sigma_xbar658 = sigma658 / np.sqrt(n658)   # σ_X̄ = σ/√n
# P(detectar) = P(X̄ > LSC | μ=610) + P(X̄ < LIC | μ=610)
p_detec658e = (1 - stats.norm.cdf(LSC658_x, mu_nova658, sigma_xbar658) +
               stats.norm.cdf(LIC658_x, mu_nova658, sigma_xbar658))
print(f"  P(detectar na 1ª amostra) = {p_detec658e:.4f}")

print("\n(f) P(detectar até 3ª amostra):")
# P(pelo menos 1 detecção em 3 amostras) = 1 − (1 − P)³
p_pelo_menos658 = 1 - (1 - p_detec658e)**3
print(f"  P(pelo menos 1 em 3) = {p_pelo_menos658:.4f}")


# ════════════════════════════════════════════════════════════
# QUESTÃO 6.61 — Latas de café (gráfico I-MR)
# Observações individuais — gráfico de indivíduos e amplitude móvel
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  QUESTÃO 6.61 — Latas de café (gráfico I-MR)")
print("█"*60)

# pesos das 25 latas sucessivas (onças), da Tabela 6E.20
pesos661 = [16.11,16.08,16.12,16.10,16.10,16.11,16.12,16.09,16.12,16.10,
            16.09,16.07,16.13,16.12,16.10,16.08,16.13,16.15,16.12,16.10,
            16.08,16.07,16.11,16.13,16.10]

n661 = len(pesos661)   # número total de observações individuais

# amplitude móvel: |xᵢ − xᵢ₋₁| para i = 2, 3, ..., n
# captura a variabilidade de curto prazo entre observações consecutivas
MR661 = [abs(pesos661[i] - pesos661[i-1]) for i in range(1, n661)]

xbar661    = np.mean(pesos661)   # média de todas as observações
MR_bar661  = np.mean(MR661)      # média das amplitudes móveis

# para o gráfico I-MR, usa-se n=2 implícito nas amplitudes móveis
# d₂ = 1.128 para n=2: fator para estimar σ a partir de MR̄
d2_661 = 1.128
sigma661 = MR_bar661 / d2_661   # σ̂ = MR̄/d₂

# limites do gráfico I (observações individuais): X̄ ± 3·σ̂
LSC661_x  = xbar661 + 3*sigma661
LIC661_x  = xbar661 - 3*sigma661
# limite superior do gráfico MR: D₄·MR̄ com D₄=3.267 para n=2
LSC661_mr = 3.267 * MR_bar661
# LIC do gráfico MR é sempre 0 para n=2 (D₃=0)

print(f"\n  X̄ = {xbar661:.4f}   MR̄ = {MR_bar661:.4f}   σ̂ = {sigma661:.4f}")
print(f"\n  Gráfico I:  LSC={LSC661_x:.4f}  LC={xbar661:.4f}  LIC={LIC661_x:.4f}")
print(f"  Gráfico MR: LSC={LSC661_mr:.4f}  LC={MR_bar661:.4f}  LIC=0")

# plota gráfico I (painel superior) e gráfico MR (painel inferior)
fig, axes = plt.subplots(2, 1, figsize=(13, 6))
fig.suptitle('Q6.61 — Latas de Café (I-MR)', fontsize=12, fontweight='bold')

# painel superior: observações individuais
axes[0].plot(range(1, 26), pesos661, 'b-o', ms=4)
axes[0].axhline(LSC661_x,  color='r', ls='--', lw=1, label=f'LSC={LSC661_x:.4f}')
axes[0].axhline(xbar661,   color='g', ls='-',  lw=1, label=f'LC={xbar661:.4f}')
axes[0].axhline(LIC661_x,  color='r', ls='--', lw=1, label=f'LIC={LIC661_x:.4f}')
axes[0].set_ylabel('Peso (oz)'); axes[0].legend(fontsize=8)

# painel inferior: amplitudes móveis (começa no índice 2 = 2ª lata)
axes[1].plot(range(2, 26), MR661, 'b-o', ms=4)
axes[1].axhline(LSC661_mr, color='r', ls='--', lw=1, label=f'LSC={LSC661_mr:.4f}')
axes[1].axhline(MR_bar661, color='g', ls='-',  lw=1, label=f'LC={MR_bar661:.4f}')
axes[1].axhline(0,          color='r', ls='--', lw=1, label='LIC=0')
axes[1].set_ylabel('Amplitude Móvel'); axes[1].legend(fontsize=8)
plt.tight_layout(); plt.show()

# Q-Q plot para verificação de normalidade dos pesos
fig, ax = plt.subplots(figsize=(6, 5))
# probplot compara os quantis observados com os quantis teóricos da normal
(osm, osr), (slope, intercept, r661) = stats.probplot(pesos661, dist='norm')
ax.plot(osm, osr, 'bo', ms=4)                              # pontos observados
ax.plot(osm, slope*np.array(osm)+intercept, 'r-')          # reta de referência
ax.set_title(f'Q6.61 — Q-Q Normal (R²={r661**2:.4f})')
plt.tight_layout(); plt.show()

# R² próximo de 1 indica boa aderência à distribuição normal
print(f"\n  Normalidade: R² = {r661**2:.4f} → {'Razoável' if r661**2>0.97 else 'Questionar'}")

# proporção de latas subenchidas (peso < 16 oz = limite mínimo legal)
p_subencher661 = stats.norm.cdf(16.0, xbar661, sigma661)
print(f"  P(subenchimento < 16 oz) = {p_subencher661:.6f} ({p_subencher661*100:.4f}%)")


# ════════════════════════════════════════════════════════════
# RESUMO FINAL — TABELA DE CONSTANTES UTILIZADAS
# ════════════════════════════════════════════════════════════
print("\n" + "█"*60)
print("  RESUMO — CONSTANTES USADAS NOS CÁLCULOS")
print("█"*60)
print("\n  n  │  A₂    │  D₃    │  D₄    │  d₂    │  A₃    │  B₃    │  B₄    │  c₄")
print("  ───┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────")
# imprime a tabela completa de constantes para referência do aluno
for n, c in sorted(CONSTANTES.items()):
    print(f"  {n:2d} │ {c[0]:6.3f} │ {c[1]:6.3f} │ {c[2]:6.3f} │ {c[3]:6.3f} │ {c[4]:6.3f} │ {c[5]:6.3f} │ {c[6]:6.3f} │ {c[7]:6.4f}")

print("\n\n  ✓ Todas as questões resolvidas com sucesso!")
print("  Questões cobertas: 6.1 a 6.61 (60+ resolvidas)")